### ISSUE TITLE
hi i got one bug 

### ISSUE THREAD

**Issue by saifuldhaka** [seb86/Auto-Load-Next-Post#11]
http://atoz2u.com/blog/10-creative-diy-pencil-stands/

Hi i tried this plugins. But found a bug.
here just load the only next post but it comes many times (same post) instead of one by one.

**Comment by seb86** [comment]
This has been answered on [WordPress.org](https://wordpress.org/support/topic/not-working-and-bug-in-load-the-post) community forum.
