### ISSUE TITLE
Both content-partial files load if they exist

### ISSUE THREAD

**Issue by rickyhanna** [seb86/Auto-Load-Next-Post#14]
In your conditionals [here](https://github.com/seb86/Auto-Load-Next-Post/blob/555e1fd6835a4ee45a15b59031026c8f4495fe39/includes/auto-load-next-post-core-functions.php#L32), if both content-partial.php files exist, they both get included.

Is this the desired behavior?

**Comment by seb86** [comment]
@rickyhanna I can't believe I had not noticed that error on my part. I didn't seem to have any problems when I was testing so I assumed it worked. My bad.

Thank you for spotting that error and can you make sure that the push goes to the "dev" branch please. Thanks.

**Comment by seb86** [comment]
@rickyhanna See [contribution guide](https://github.com/seb86/Auto-Load-Next-Post/blob/master/CONTRIBUTING.md).

**Comment by seb86** [comment]
@rickyhanna If you would like to be credited for your contribution when I release the next update in the next few days, please follow the [guidlines](https://github.com/seb86/Auto-Load-Next-Post/blob/master/CONTRIBUTING.md) and repush to the correct branch. Thank you.

**Comment by rickyhanna** [comment]
Alrighty.  Will do if I get the time.

**Comment by seb86** [comment]
@rickyhanna I want to push an update later today so if you could simply make the push within the next 5 hours. That would be great. Otherwise I will have to do it my self and you won't be credited as a contributor.

**Comment by rickyhanna** [comment]
Can you please tell me how to push to the dev branch?

**Comment by seb86** [comment]
See this article for more help. https://help.github.com/articles/pushing-to-a-remote/

**Comment by seb86** [comment]
Fixed.
