### ISSUE TITLE
Upgrading to work with multisite

### ISSUE THREAD

**Issue by webwaldo** [seb86/Auto-Load-Next-Post#16]
Hey,

Loving the plugin. Have you thought about upgrading to work with multisite ?

If you could give me some direction I would be happy to try and help convert it over? 
I am not 100% but will it require more than just altering the plugin to allow it check if it's in multisite and pull the settings from the appropriate place ?

ala - http://wordpress.stackexchange.com/questions/166484/get-option-compatible-with-wordpress-network-multisite ?

**Comment by webwaldo** [comment]
Will move this over to wp.org instead of here :O

**Comment by seb86** [comment]
@webwaldo I have not yet tested the plugin on a multisite setup but I don't think any modification is needed. You simply just activate the plugin for the site you want to use it on and it will load it's own settings. If you activate it globally, then you might have a problem but as I said, not yet tested.

Thank you for writing this issue. I will put it up for questioning.

**Comment by seb86** [comment]
Tested the plugin on a multinetwork. No problems found.
