### ISSUE TITLE
Cannot use 'in' operator to search for 'length' in true

### ISSUE THREAD

**Issue by sahidhossen** [seb86/Auto-Load-Next-Post#18]
Not working with jQuery-1.11.3.  Its says cannot use 'in' operator. Please solve this issue
Thanks.

**Comment by seb86** [comment]
Can you be more specific as to the bug. Maybe a line number in the Javascript.

**Comment by sahidhossen** [comment]
Please check the images. 

![github-issue](https://cloud.githubusercontent.com/assets/12063077/10562591/7669c582-7585-11e5-9d3c-18824eb20eb2.png)

**Comment by seb86** [comment]
I have not been able to re-create this bug. Please update the plugin and check again. Thank you.
