### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by iamcoreyg** [seb86/Auto-Load-Next-Post#38]
Documentation on how to support custom themes is not thorough enough and no error messages are supplied so it's very difficult to debug.

**Comment by seb86** [comment]
@iamcoreyg I am actually in the middle of improving the documentation. No eta at the moment.

**Comment by seb86** [comment]
@iamcoreyg If you have the debug mode and script mode set to true in your wp-config.php file you should get some errors in the console log when you are using the browser developer tools.

Could you be more specific on the type of error messages you need supplied?

**Comment by seb86** [comment]
Documentation has been recently improved. Can close this for now.

**Comment by iamcoreyg** [comment]
@seb86 Sweet, good work man
