### ISSUE TITLE
scrollSpy is not a function.

### ISSUE THREAD

**Issue by mstojanovv** [seb86/Auto-Load-Next-Post#45]
Hello.

There is some confilict with scrollSpy when autoloader-post trying to initialize.
http://postimg.org/image/7sxq548ff/
http://s9.postimg.org/ll7eua7fz/autoload_post_2.png
Any idea how to fix this?

**Comment by seb86** [comment]
If you are getting this error it is because there is a JavaScript conflict with another plugin and is causing it to not load. I see you are using the plugin "NextCellent Gallery - NextGEN Legacy". I have not tested my plugin with this but it may be the plugin it does not work with.

[scrollSpy](https://github.com/sxalexander/jquery-scrollspy) is also created by another developer so it would be better to contact that person about this issue.

**Comment by mstojanovv** [comment]
Hi.
Thank you for the reply.
I think that you need to encapsulate jQuery( document ).ready( function() { }) with
```
(function($) {

})(jQuery);
```
This fixed the error now.
Thanks

**Comment by seb86** [comment]
@mstojanovv Just to be clear, are you saying it works once you changed the Javascript to be encapsulated as you have shown or you noticed you incorrectly setup the container selector?

**Comment by mstojanovv** [comment]
Hi, got it working.. some theme scripts was causing the problem.

Now works good but not infinite loop throught all post. Ex load only 10-15 and when i get to the bottom i can see the next post link but its not fetched from the plugin, the plugin doesnt get this next post link and is not set as next post so the post loading stops here.

http://postimg.org/image/k4p8deecv/full/
Any suggestions for this?
Thanks

**Comment by seb86** [comment]
You may have scrolled to the bottom to fast for the javascript to work.

**Comment by seiyar26** [comment]
Hi mstojanovv have you success to resolve your problem ?

**Comment by mstojanovv** [comment]
Hi. Yes i resolved.
There was some missing element closing and thats was causing the problem. After i formated the html well worked good.

**Comment by seiyar26** [comment]
Thanks for your answer could you explain me how did you do it ?

**Comment by mstojanovv** [comment]
Hi.

I had some unclosed div element. You should re-check your code. I just rewrite the code and worked good.

**Comment by seb86** [comment]
This error is still in question as it is affected by certain themes.

**Comment by seb86** [comment]
Might not be an issue in the future once issue #58 has been achieved.

**Comment by seb86** [comment]
Maybe removing the use of ScrollSpy in light of new JavaScript resource called [Within ViewPort](https://github.com/seb86/Auto-Load-Next-Post/issues/65).

**Comment by seb86** [comment]
Does not appear to be an issue any more. Closing issue.
