### ISSUE TITLE
Doesn't work with the Yoast SEO Plugin

### ISSUE THREAD

**Issue by aurooba** [seb86/Auto-Load-Next-Post#53]
I couldn't get the plugin to work properly on one of my sites, and I narrowed it down to Yoast SEO (v 3.1.2). If the plugin is activated, Auto Load Next Post (v 1.4.6) doesn't load things properly and the entire header of the footer is regenerated under each post with all the meta properties. I couldn't find a way to have both Yoast SEO and Auto Load Next Post activated at the same time.

Is there something I'm missing?

**Comment by aurooba** [comment]
@seb86 hey, is there some way I can fix this?

**Comment by seb86** [comment]
@aurooba Sorry for the late response. For some reason, I was not notified of this new issue via email or under GitHub notifications. Could you please create a support ticket on the community forum so others can join in on this issue and also explain more about what is happening and possibly provide screenshots also. Thank you.
