### ISSUE TITLE
Problem with loading posts

### ISSUE THREAD

**Issue by Peter74** [seb86/Auto-Load-Next-Post#56]
Hi,
I was try to set and run your plugin, because is what I need. I get it work with my theme.
But than I spend 4 hours to research where is problem:
When you load page, there is one post, if you start scroll, it start load another and another and another....
...even if you load page and scroll between first 2-3 posts, it load another posts.
I read this as people report it to you and you answer them, that this is cause by wrong template but...

...today morning I open your demo and it is work exactly wrong as on my site.

try to open your demo and scroll between 2 - 3 posts and you will get it (you do not need to scroll between 2 - 3 posts, it is enough to play with first post - scroll him up and down)

It is fire loading next post almost every time, when divider/post or how you load another post is cross fire point - not only on last post, but each post...

**Comment by Peter74** [comment]
...on other hands I would like to participate to help with translation for Slovak language, but I can not join team on Transifex, because Slovak Language does not exist.

**Comment by seb86** [comment]
@Peter74 Thank you for the translation. I will add it in the next update.
