### ISSUE TITLE
Loading only title

### ISSUE THREAD

**Issue by argolika** [seb86/Auto-Load-Next-Post#64]
While i have setup this normally at argolika.gr and loads at the end of the article the next it loads only the article link and not the content.
Theme: MagazineVibe

Content Container 	
div.edgtf-blog-holder.edgtf-blog-single
Post Title Selector 	
div.edgtf-post-title-area
Post Navigation Container 	
div.edgtf-blog-single-navigation
Comments Container 	
div.edgtf-comment-holder,div.edgtf-comment-form

The site is currently on Maintenance Mode

**Comment by seb86** [comment]
Support requests are to be made on the [community forum](https://wordpress.org/support/plugin/auto-load-next-post), not here.
