### ISSUE TITLE
Issue with Loading even with Default WP Theme

### ISSUE THREAD

**Issue by eliaguilar** [seb86/Auto-Load-Next-Post#66]
Having issue loading auto next post. Everything seems to be configured properly. 
http://jdtemp.hazlomedia.com/blog/new-post-show-fallback/

**Comment by eliaguilar** [comment]
Was I not supposed post support questions here?

**Comment by seb86** [comment]
GitHub is for bug reports and contributions only. If you have a support question or a request, don't post here. Use [WordPress.org](https://wordpress.org/support/plugin/auto-load-next-post) for community support.
