### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by mhaagens** [seb86/Auto-Load-Next-Post#8]
I installed the plugin and created the content partial, but I'm getting a "undefined is not a function" error on my page. Do I have to include Scrollspy for this to work? If so which version?

Great plugin by the way!

Uncaught TypeError: undefined is not a functionauto-load-next-post.min.js?ver=1.0.0:1 initialise_Scrollspyauto-load-next-post.min.js?ver=1.0.0:1 (anonymous function)jquery.js?ver=1.11.1:2 m.Callbacks.jjquery.js?ver=1.11.1:2 m.Callbacks.k.fireWithjquery.js?ver=1.11.1:2 m.extend.readyjquery.js?ver=1.11.1:2 J

**Comment by seb86** [comment]
@mhaagens Scrollspy is included with the plugin and yes it is required for it to work. Re-enable Scrollspy if you have disabled it and it should work again.

I'm glad you like it. Please forward [your review](https://wordpress.org/support/view/plugin-reviews/auto-load-next-post?rate=5#postform) on the WordPress.org repository.

Thank you.

**Comment by mhaagens** [comment]
Scrollspy is enabled and included but I still get the error message.
Any idea what is causing this?


![jserror](https://cloud.githubusercontent.com/assets/3270517/7089030/12826984-df99-11e4-9a67-b8f243a9eb1f.gif)

**Comment by seb86** [comment]
Do you have other plugins that use Scrollspy?

**Comment by mhaagens** [comment]
These are the plugins I'm using;
```
     './bower_components/jquery/dist/jquery.min.js',
     './bower_components/jquery-hoverIntent/jquery.hoverIntent.js',
     './bower_components/waypoints/lib/jquery.waypoints.min.js',
     './bower_components/owl2/src/js/owl.carousel.js'
```

No other plugins active that use Scrollspy that I know of.
I'm using _s as my theme base, don't know if that matters?

Thanks for helping me out!

**Comment by seb86** [comment]
I will have to do so testing. It is possible there is a conflict somewhere. Thank you for reporting the issue. I will get back to with what I find.

**Comment by mhaagens** [comment]
Awesome, appreciate it!

**Comment by seb86** [comment]
@mhaagens I have not been able to replicate this issue.

**Comment by seb86** [comment]
@mhaagens Please try using the latest version of the plugin.
